# configs/config.yaml
server:
  port: 8080
  host: 0.0.0.0
  debug: true
  timeout: 30s


app:
  name: "My App"
  version: "1.0.0"
  env: "development"
  jwt_secret: "your-256-bit-secret"
  api_key: "your-api-key-here"